---
- name: Install Docker Module for Python
  pip:
    name: docker

- name: Start polkadots containers
  docker_container:
    name: "{{ polkadot_node_name }}_{{ item }}"
    recreate: yes
    image: chevdor/polkadot:latest
    command: "polkadot --name '{{ polkadot_node_name }}_{{ item }}' "
  with_sequence: count={{ polkadot_node_count }}
